# Generated by Django 6.0.3 on 2026-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
